// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyleMate.Data;

#nullable disable

namespace StyleMateManager.API.Migrations
{
    [DbContext(typeof(StyleMateDataContext))]
    [Migration("20240502120555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StyleMate.Data.EntityModels.ImageUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("StyleMateGarmentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("StyleMateGarmentId");

                    b.ToTable("ImageUrls");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.StyleMateGarment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StyleMateGarments");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GarmentTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StyleMateGarmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleMateGarmentId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.UserLikedGarment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GarmentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LikedGarments");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.UserLikedTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LikedTags");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.ImageUrl", b =>
                {
                    b.HasOne("StyleMate.Data.EntityModels.StyleMateGarment", null)
                        .WithMany("ImageUrls")
                        .HasForeignKey("StyleMateGarmentId");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.Tag", b =>
                {
                    b.HasOne("StyleMate.Data.EntityModels.StyleMateGarment", null)
                        .WithMany("Tags")
                        .HasForeignKey("StyleMateGarmentId");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.UserLikedGarment", b =>
                {
                    b.HasOne("StyleMate.Data.EntityModels.User", null)
                        .WithMany("LikedGarments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.UserLikedTags", b =>
                {
                    b.HasOne("StyleMate.Data.EntityModels.User", null)
                        .WithMany("LikedTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.StyleMateGarment", b =>
                {
                    b.Navigation("ImageUrls");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.User", b =>
                {
                    b.Navigation("LikedGarments");

                    b.Navigation("LikedTags");
                });
#pragma warning restore 612, 618
        }
    }
}
