// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyleMate.Data;

#nullable disable

namespace StyleMateManager.API.Migrations
{
    [DbContext(typeof(StyleMateDataContext))]
    partial class StyleMateDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StyleMate.Data.EntityModels.ImageUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("StyleMateGarmentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("StyleMateGarmentId");

                    b.ToTable("ImageUrls");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.StyleMateGarment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StyleMateGarments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Werkt gw man",
                            Price = 0f,
                            SiteUrl = ""
                        });
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GarmentTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StyleMateGarmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleMateGarmentId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.ImageUrl", b =>
                {
                    b.HasOne("StyleMate.Data.EntityModels.StyleMateGarment", null)
                        .WithMany("ImageUrls")
                        .HasForeignKey("StyleMateGarmentId");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.Tag", b =>
                {
                    b.HasOne("StyleMate.Data.EntityModels.StyleMateGarment", null)
                        .WithMany("Tags")
                        .HasForeignKey("StyleMateGarmentId");
                });

            modelBuilder.Entity("StyleMate.Data.EntityModels.StyleMateGarment", b =>
                {
                    b.Navigation("ImageUrls");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
